Feat/simulate
NCKU-CCS/energy-trading-platform pull request #20
Opened 2020-07-01 15:55 UTC by grandq33769

- Add simulate powerdata feature

- Add simulate bidsubmit feature

- Add .pre-commit config

- Update makefile

- Update simulate-related doc

2020-07-02 07:08 UTC, ttw225 requested changes
有一些小地方可以調整一下 主要是註解的部分
另外我個人使用 black 來做排版的時候會用下面的指令
`black -l 120 --skip-string-normalization <file>`
第一個是預設長度使用 120，會少換不少行；第二個是不管單雙引號

2020-07-02 07:08 UTC, ttw225 commented on .flake8
> +ignore = E501,E731,W503
可以在上面註解一下
`W503 line break occurred before a binary operator`

2020-07-02 07:08 UTC, ttw225 commented on .pylintrc
> +disable=C0111, R0903, W1203, E0611, E0401, R0913, R0902, C0330
這邊也可以加一下註解

2020-07-02 07:08 UTC, ttw225 commented on Pipfile
> +commitizen = "*"
為了避免未來爆炸可以加一下版本

2020-07-02 07:37 UTC, grandq33769 commented on .pylintrc
> +disable=C0111, R0903, W1203, E0611, E0401, R0913, R0902, C0330
Fixed in e881d5278465f478d4d7b1a67187768ab5dc744f .

2020-07-02 07:37 UTC, grandq33769 commented on .flake8
> +ignore = E501,E731,W503
Fixed in e881d5278465f478d4d7b1a67187768ab5dc744f .

2020-07-02 07:41 UTC, grandq33769 commented on Pipfile
> +commitizen = "*"
Fix in 36c25210d4448b350318b26f3a07f0e8430dda6d .

2020-07-03 13:34 UTC, grandq33769 commented
有關 black 的設定，目前有2個做法：
1. 修改 pyproject.toml [d287979bc13562d5250845d444a9c269182da538]
2. 在 vscode 上修改 black 的 args
<img width="428" alt="設定_—_energy-trading-platform" src="https://user-images.githubusercontent.com/16376604/86474193-e390e000-bd74-11ea-92da-afd606ba1271.png">

另外，關於程式碼的的實作，如果有問題也請不用客氣，我立馬修改。

2020-07-07 06:22 UTC, ttw225 commented
我的意思是，有些檔案看起來只是換了單雙引號

2020-07-07 06:23 UTC, ttw225 commented
LGTM

2020-07-07 06:24 UTC, ttw225 approved these changes
LGTM

2020-07-07 08:38 UTC, merged