docs: new dr api document
NCKU-CCS/energy-trading-platform pull request #24
Opened 2020-11-13 07:06 UTC by iknowright

Create DR API doc for cooperation with Prof Yang's team.

2020-11-13 07:56 UTC, ttw225 requested changes

2020-11-13 07:56 UTC, ttw225 commented on apiary_dr.apib
> +        + bearer: `OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR` - Authentication Bearer Token
這邊實際上還會回 `is_aggregator`，雖然對他們來說應該沒差，但好像可以寫一下

```
+ `is_aggregator`: False (bool) - is aggregator or not
```

2020-11-13 07:56 UTC, ttw225 commented on apiary_dr.apib
> +        + end_time (required, string)
這邊可以加個範例，順便說明一下我們的時間格式

```
### GET BIDS [GET /DR_bid{?start_time,end_time}]

+ Parameters
        + start_time: `2020-01-01 10:00` (required, string) - query start time (YYYY-MM-DD HH:mm)
        + end_time: `2020-01-01 11:00 ` (required, string) - query end time (YYYY-MM-DD HH:mm)
```

2020-11-13 07:56 UTC, ttw225 commented on apiary_dr.apib
> +            Authorization: `Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR
token 右邊少一個 ` XD

2020-11-13 07:56 UTC, ttw225 commented on apiary_dr.apib
> +        + end_time: `2020-11-11 11:00:00` (string) - DR end time
看 end_time 要不要改成 12 點

2020-11-13 07:56 UTC, ttw225 commented on apiary_dr.apib
> +            + blockchain_url: `https://ropsten.etherscan.io/tx/0x07178bc6d022a826d7f85b64f00b77bf878d04519cfbdc6e33aacd802b191435` (string) - url
這邊還不會回 blockchain url ~~

這樣應該回 200 or 400 就可以

2020-11-13 15:08 UTC, iknowright commented
comments above are fixed in 19d9fd6738bd2ef82e10ec8a293b55a103f6a4ea

In addition:
* Prettified document description rendered on `apiary.io`.
* fix extra typo by enabling spell checker on `.apib` file.

2020-11-17 06:58 UTC, ttw225 commented on apiary_dr.apib
> +        + end_time (required, string)
there is a space at the end of end_time, my fault XD
```
+ end_time: `2020-01-01 11:00 ` (required, string) - query end time (YYYY-MM-DD HH:mm)
-------------------------------^ extra white space
```

2020-11-17 06:59 UTC, ttw225 approved these changes
Please remove the extra white space and directly merge this branch~

2020-11-17 07:07 UTC, iknowright commented on apiary_dr.apib
> +        + end_time (required, string)
fixed in 32fe0bbad01bda67191a527171aa15703efa92b8

2020-11-17 07:07 UTC, merged