DR-smart-contract-upload
NCKU-CCS/energy-trading-platform pull request #31
Opened 2020-12-02 08:43 UTC by iknowright

Upload DR_bid where blockchain_url is null.

2020-12-02 15:14 UTC, ttw225 requested changes
有些地方需要再調整一下下

2020-12-02 15:14 UTC, ttw225 commented on pt/blockchain/trigger.py
> +        end_time = f"end_time: {bid.end_time.strftime('%Y-%m-%d %H:%M:%S')}"
沒有成交的 DR 的 `end_time` 會是 None，這邊需要做個檢查，我在 GET DR_result 時有發現後做了處理可以參考一下

`"end_time": bid.end_time.strftime("%Y-%m-%d %H:%M:%S") if bid.end_time else None`

2020-12-02 15:14 UTC, ttw225 commented on pt/blockchain/trigger.py
> +        ))
可以考慮把這些數值包成 tuple，join 的時候就可以用 one line for loop 包起來，reuse 也方便就不用打兩次這些欄位

2020-12-02 15:14 UTC, ttw225 commented on pt/blockchain/trigger.py
> +        bid.blockchain_url = f"https://ropsten.etherscan.io/tx/{tx_hash}"
這邊的 type 不知道會不會有問題 (HexBytes -> str)，如果沒問題請幫我直接 close 這個 issue, thanks!

2020-12-03 01:58 UTC, iknowright commented on pt/blockchain/trigger.py
> +        bid.blockchain_url = f"https://ropsten.etherscan.io/tx/{tx_hash}"
`pt/blockchain/contract.py` 的 `json.loads(Web3.toJSON(self.contract.events.matched_log().processReceipt(receipt)))` 會將 Web3 object 轉成 JSON str, 然後再用 loads 就不會有這個問題了。不然的話原本的 obj 確實很難 parse.

2020-12-03 02:58 UTC, iknowright commented on pt/blockchain/trigger.py
> +        end_time = f"end_time: {bid.end_time.strftime('%Y-%m-%d %H:%M:%S')}"
fixed in b24c65e6b3ec942afc998484ba6997f998535ce6
我發現不用 check None 也可以正常顯示（我認爲這個是 f-string 的性質），不用 specify strftime, datetime 也會自動轉爲 `%Y-%m-%d %H:%M:%S` 。

2020-12-03 02:59 UTC, iknowright commented on pt/blockchain/trigger.py
> +        ))
fixed in b24c65e6b3ec942afc998484ba6997f998535ce6
搭配 wanted columns (可以排序) 與 query_row.__dict__，可以將 row 轉成 dict, 於此同時可以用 `items()` 處理 log_text 的 generation.

2020-12-03 03:27 UTC, iknowright commented
加入上鍊 Timeout in f60c5d331b858acb7ce934abf258a01e53d4bdd9

2020-12-29 09:35 UTC, iknowright commented
每分鐘確認是否有新的 accepted dr, 上傳並確認
每天 00：10 確認是否有殘留的 denied dr , 上傳並確認否決

2020-12-30 08:04 UTC, ttw225 requested changes
修正一下 query filter 即可, thx!

2020-12-30 08:04 UTC, ttw225 commented on pt/blockchain/trigger.py
> +            DRBidModel.result is None,
`is` -> `==` or `.is_()`

下面 `accepted_dr_upload()` 記得也一起改一下

2021-01-04 02:04 UTC, ttw225 approved these changes
LGTM

2021-01-04 02:19 UTC, merged