feat: add counterpart for dr bid result
NCKU-CCS/energy-trading-platform pull request #38
Opened 2021-01-17 07:21 UTC by iknowright

修改 dr_result api, 回傳 counterpart

對象: 如果登入的人是 aggregator，對象顯示 executor; 如果登入的人是 bems， 對象顯示 acceptor
地址: 如果登入的人是 aggregator，地址顯示 executor 的地址; 如果登入的人是 bems， 地址顯示 acceptor 的地址

2021-01-19 07:07 UTC, ttw225 requested changes
function name 可以調整一下, thanks!

2021-01-19 07:07 UTC, ttw225 commented on pt/endpoints/dr/model.py
> +    return User.query.filter_by(account=account).first()
這個 function 可以不只用在 counterpart，可以考慮一下 function name 改為 `get_user` 或是 `get_user_object` 看會不會比較合適

2021-01-20 03:47 UTC, iknowright commented on pt/endpoints/dr/model.py
> +    return User.query.filter_by(account=account).first()
fix in 93842c19340ccd9988dd4f93c9951e9685e4182e

2021-01-21 04:32 UTC, ttw225 approved these changes
LGTM, thanks!

2021-01-21 05:06 UTC, merged