New eth bidsubmit
NCKU-CCS/energy-trading-platform pull request #39
Opened 2021-01-18 14:30 UTC by iknowright

replace of #36 , new bid submit should merge to branch `dr-upload-revert`

2021-01-19 08:11 UTC, ttw225 requested changes
冒號！

2021-01-19 08:11 UTC, ttw225 commented on pt/blockchain/trigger.py
> +                    bid.win: 0
冒號！

2021-01-20 01:07 UTC, iknowright commented on pt/blockchain/trigger.py
> +                    bid.win: 0
Thanks, its fixed by 5298eedac499a8dd305925c3af7ba9df00e43a6e

2021-01-20 03:03 UTC, ttw225 approved these changes
LGTM~

2021-01-20 03:04 UTC, merged