tizan/user
NCKU-CCS/energy-trading-platform pull request #42
Opened 2021-02-07 07:23 UTC by Jhe-Yun

- user database修改
- 修正tizan/kinmen/user錯誤
- 前端測試完成(除了eth_address)

2021-02-08 04:04 UTC, iknowright commented on pt/app.py
> -    socketio.run(app, host="0.0.0.0", port=os.environ.get("PORT", 5000), ssl_context=app.config['SSL_CONTEXT'])
如果是 production 則是相反過來 (swap 註解)。
---
這裡可能要確認一下目前  production server 會不會動

2021-02-08 04:07 UTC, iknowright commented on user_init.sql
> +            'tpc');
加一下 newline 會比較好，不然會有一個 symbol 警示

2021-02-08 04:10 UTC, iknowright commented
* 好像忘記做 db migration 了？ `python manage.py db migrate`， migrations 的 change 沒有產到哦
* 有一些 style 上的差別，看能不能改會比較統一 `''` to `"`, single quote to double quote

2021-02-08 04:12 UTC, iknowright requested changes
* 好像忘記做 db migration 了？ `python manage.py db migrate`， migrations 的 change 沒有產到哦
* 有一些 style 上的差別，看能不能改會比較統一 `''` to `"`, single quote to double quote

2021-02-08 04:53 UTC, grandq33769 commented
> * 好像忘記做 db migration 了？ `python manage.py db migrate`， migrations 的 change 沒有產到哦
> * 有一些 style 上的差別，看能不能改會比較統一 `''` to `"`, single quote to double quote

或許試看看 `black` ?

2021-02-08 04:58 UTC, Jhe-Yun commented
請問 `black` 是什麼？

2021-02-08 05:20 UTC, grandq33769 commented
> 請問 `black` 是什麼？

格式化工具

應該是 `make black` 就好

https://github.com/psf/black

![Screenshot_20210208-131803.png](https://user-images.githubusercontent.com/16376604/107178981-4d125480-6a10-11eb-953b-d10d1c8ecc88.png)

2021-02-08 09:39 UTC, grandq33769 approved these changes
LGTM

2021-02-08 09:42 UTC, iknowright approved these changes
LGTM, thx!

2021-02-10 14:59 UTC, grandq33769 commented
@Jhe-Yun MR should be better to be merged by yourself because you can control the code dependency more easily.

2021-02-10 15:01 UTC, Jhe-Yun commented
好的，謝謝

2021-02-10 15:01 UTC, merged