Tizan/dr
NCKU-CCS/energy-trading-platform pull request #46
Opened 2021-02-22 14:11 UTC by Jhe-Yun

完成以下事項

- TPC GET DR bids 可以取得所有 Aggregator 的投標
- TPC GET DR result 可以取得所有已決標的 Aggregator 投標
- Aggregator GET DR bids 可以取得 (a)所有 user 的投標 和 (b)自己的投標
- Aggregator GET DR result 可以取得所有 (a)已決標的 user 投標 和 (b)被決標的 dr 投標
- Users GET DR bids 可以取得自己的投標
- Users GET DR result 可以取得所有被決標的 dr 投標

2021-02-23 03:23 UTC, iknowright commented on pt/endpoints/dr/resource.py
> +        aggre_accounts = [user.account for user in User.query.filter(User.role.in_(["aggregator"])).all()]
如果是針對自己的 table 做 query 可以使用
`User.query.filter_by(role="aggregator").all()`
use filter_by 比較直覺， 用 in_ 的 scenario 有點不適合

2021-02-23 03:30 UTC, iknowright requested changes
看看 query 有沒有類似不用 in_ 就可以 filter 的狀況。如果可以再化簡一點會更好，extend roles 的部分好像沒有很直覺。

2021-02-23 09:48 UTC, Jhe-Yun commented on pt/endpoints/dr/resource.py
> +        aggre_accounts = [user.account for user in User.query.filter(User.role.in_(["aggregator"])).all()]
OK，本來想說統一用filter

2021-02-23 11:52 UTC, Jhe-Yun commented
咦 我不知道要怎麼再簡化
有好建議嗎

2021-02-25 07:55 UTC, Jhe-Yun commented
- 加入部分測試
- 語法修正

2021-02-25 08:10 UTC, iknowright approved these changes
LGTM, Thanks!

2021-02-25 10:02 UTC, merged